export type ThemeColorKey =
  | "background"
  | "foreground"
  | "card"
  | "cardForeground"
  | "popover"
  | "popoverForeground"
  | "primary"
  | "primaryForeground"
  | "secondary"
  | "secondaryForeground"
  | "muted"
  | "mutedForeground"
  | "accent"
  | "accentForeground"
  | "destructive"
  | "destructiveForeground"
  | "border"
  | "input"
  | "ring"
  | "gold"
  | "goldSoft"
  | "goldDark"
  | "ivory"
  | "onyx"
  | "sidebar"
  | "sidebarForeground"
  | "sidebarPrimary"
  | "sidebarPrimaryForeground"
  | "sidebarAccent"
  | "sidebarAccentForeground"
  | "sidebarBorder"
  | "sidebarRing"
  | "iconColor"
  | "displayFont"
  | "bodyFont"
  | "buttonGradientStart"
  | "buttonGradientEnd"
  | "buttonForeground";

export type ThemeColors = Partial<Record<ThemeColorKey, string>>;

export type ThemePreset = {
  id: string;
  name: string;
  description: string;
  colors: ThemeColors;
  category: "Dark Luxury" | "Soft Elegant" | "Bold Jewel" | "Cool Modern";
};

export const THEME_FONT_OPTIONS = {
  display: [
    {
      label: "Cormorant Garamond",
      value: '"Cormorant Garamond", "Playfair Display", ui-serif, Georgia, serif',
    },
    {
      label: "Playfair Display",
      value: '"Playfair Display", "Cormorant Garamond", ui-serif, Georgia, serif',
    },
    {
      label: "Cinzel",
      value: '"Cinzel", "Cormorant Garamond", ui-serif, Georgia, serif',
    },
    {
      label: "Merriweather",
      value: '"Merriweather", "Cormorant Garamond", ui-serif, Georgia, serif',
    },
  ],
  body: [
    {
      label: "Inter",
      value: '"Inter", ui-sans-serif, system-ui, sans-serif',
    },
    {
      label: "Manrope",
      value: '"Manrope", "Inter", ui-sans-serif, system-ui, sans-serif',
    },
    {
      label: "DM Sans",
      value: '"DM Sans", "Inter", ui-sans-serif, system-ui, sans-serif',
    },
    {
      label: "Source Sans 3",
      value: '"Source Sans 3", "Inter", ui-sans-serif, system-ui, sans-serif',
    },
  ],
} as const;

export const THEME_COLOR_FIELDS: Array<{
  key: ThemeColorKey;
  label: string;
  section: "Base" | "Brand" | "Sidebar";
}> = [
  { key: "background", label: "Background", section: "Base" },
  { key: "foreground", label: "Foreground", section: "Base" },
  { key: "card", label: "Card", section: "Base" },
  { key: "cardForeground", label: "Card Foreground", section: "Base" },
  { key: "popover", label: "Popover", section: "Base" },
  { key: "popoverForeground", label: "Popover Foreground", section: "Base" },
  { key: "primary", label: "Primary", section: "Base" },
  { key: "primaryForeground", label: "Primary Foreground", section: "Base" },
  { key: "secondary", label: "Secondary", section: "Base" },
  { key: "secondaryForeground", label: "Secondary Foreground", section: "Base" },
  { key: "muted", label: "Muted", section: "Base" },
  { key: "mutedForeground", label: "Muted Foreground", section: "Base" },
  { key: "accent", label: "Accent", section: "Base" },
  { key: "accentForeground", label: "Accent Foreground", section: "Base" },
  { key: "destructive", label: "Destructive", section: "Base" },
  { key: "destructiveForeground", label: "Destructive Foreground", section: "Base" },
  { key: "border", label: "Border", section: "Base" },
  { key: "input", label: "Input", section: "Base" },
  { key: "ring", label: "Ring", section: "Base" },
  { key: "gold", label: "Gold", section: "Brand" },
  { key: "goldSoft", label: "Gold Soft", section: "Brand" },
  { key: "goldDark", label: "Gold Dark", section: "Brand" },
  { key: "ivory", label: "Ivory", section: "Brand" },
  { key: "onyx", label: "Onyx", section: "Brand" },
  { key: "sidebar", label: "Sidebar", section: "Sidebar" },
  { key: "sidebarForeground", label: "Sidebar Foreground", section: "Sidebar" },
  { key: "sidebarPrimary", label: "Sidebar Primary", section: "Sidebar" },
  { key: "sidebarPrimaryForeground", label: "Sidebar Primary Foreground", section: "Sidebar" },
  { key: "sidebarAccent", label: "Sidebar Accent", section: "Sidebar" },
  { key: "sidebarAccentForeground", label: "Sidebar Accent Foreground", section: "Sidebar" },
  { key: "sidebarBorder", label: "Sidebar Border", section: "Sidebar" },
  { key: "sidebarRing", label: "Sidebar Ring", section: "Sidebar" },
];

export const THEME_ICON_FIELDS: Array<{
  key: ThemeColorKey;
  label: string;
  section: "Icon";
}> = [{ key: "iconColor", label: "Icon Color", section: "Icon" }];

export const THEME_TYPOGRAPHY_FIELDS: Array<{
  key: ThemeColorKey;
  label: string;
  section: "Typography";
}> = [
  { key: "displayFont", label: "Display Font", section: "Typography" },
  { key: "bodyFont", label: "Body Font", section: "Typography" },
];

export const THEME_BUTTON_FIELDS: Array<{
  key: ThemeColorKey;
  label: string;
  section: "Buttons";
}> = [
  { key: "buttonGradientStart", label: "Gradient Start", section: "Buttons" },
  { key: "buttonGradientEnd", label: "Gradient End", section: "Buttons" },
  { key: "buttonForeground", label: "Text Color", section: "Buttons" },
];

export const DEFAULT_THEME_FORM: Record<ThemeColorKey, string> = {
  background: "#241f19",
  foreground: "#f7f1e3",
  card: "#2b251f",
  cardForeground: "#f7f1e3",
  popover: "#2b251f",
  popoverForeground: "#f7f1e3",
  primary: "#d8b46b",
  primaryForeground: "#241f19",
  secondary: "#3a3128",
  secondaryForeground: "#f7f1e3",
  muted: "#342d25",
  mutedForeground: "#c8bca7",
  accent: "#3d342a",
  accentForeground: "#f7f1e3",
  destructive: "#c45c54",
  destructiveForeground: "#faf7f2",
  border: "#5b4b3b",
  input: "#3a3027",
  ring: "#d8b46b",
  gold: "#d8b46b",
  goldSoft: "#f0d7a0",
  goldDark: "#b98d3f",
  ivory: "#f7f1e3",
  onyx: "#1a1410",
  sidebar: "#1d1813",
  sidebarForeground: "#efe5d2",
  sidebarPrimary: "#d8b46b",
  sidebarPrimaryForeground: "#241f19",
  sidebarAccent: "#342b22",
  sidebarAccentForeground: "#f7f1e3",
  sidebarBorder: "#4a3d31",
  sidebarRing: "#d8b46b",
  iconColor: "#c8bca7",
  displayFont: '"Cormorant Garamond", "Playfair Display", ui-serif, Georgia, serif',
  bodyFont: '"Inter", ui-sans-serif, system-ui, sans-serif',
  buttonGradientStart: "#f0d7a0",
  buttonGradientEnd: "#b98d3f",
  buttonForeground: "#241f19",
};

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: "noir-gold",
    name: "Noir Gold",
    description: "Deep black with warm gold accents.",
    category: "Dark Luxury",
    colors: {
      background: "#1b1714",
      foreground: "#f6efe3",
      card: "#251f1b",
      cardForeground: "#f6efe3",
      popover: "#251f1b",
      popoverForeground: "#f6efe3",
      primary: "#d8b46b",
      primaryForeground: "#1b1714",
      secondary: "#372f28",
      secondaryForeground: "#f6efe3",
      muted: "#2a241f",
      mutedForeground: "#cdbda3",
      accent: "#3f352d",
      accentForeground: "#f6efe3",
      border: "#5a4a3e",
      input: "#332b25",
      ring: "#d8b46b",
      gold: "#d8b46b",
      goldSoft: "#edd7a3",
      goldDark: "#b88b3a",
      ivory: "#f6efe3",
      onyx: "#120f0d",
      sidebar: "#171311",
      sidebarForeground: "#efe4cf",
      sidebarPrimary: "#d8b46b",
      sidebarPrimaryForeground: "#1b1714",
      sidebarAccent: "#2f2721",
      sidebarAccentForeground: "#f6efe3",
      sidebarBorder: "#463a31",
      sidebarRing: "#d8b46b",
      iconColor: "#cdbda3",
      displayFont: '"Cormorant Garamond", "Playfair Display", ui-serif, Georgia, serif',
      bodyFont: '"Inter", ui-sans-serif, system-ui, sans-serif',
      buttonGradientStart: "#edd7a3",
      buttonGradientEnd: "#b88b3a",
      buttonForeground: "#1b1714",
    },
  },
  {
    id: "ivory-blush",
    name: "Ivory Blush Gold",
    description: "Soft ivory with refined champagne warmth.",
    category: "Soft Elegant",
    colors: {
      background: "#f7f1ea",
      foreground: "#201915",
      card: "#fffaf4",
      cardForeground: "#201915",
      popover: "#fffaf4",
      popoverForeground: "#201915",
      primary: "#c89b4a",
      primaryForeground: "#fffaf4",
      secondary: "#eadfce",
      secondaryForeground: "#201915",
      muted: "#efe6da",
      mutedForeground: "#6f5f54",
      accent: "#f1e5d6",
      accentForeground: "#201915",
      border: "#dcc9b2",
      input: "#eadfce",
      ring: "#c89b4a",
      gold: "#c89b4a",
      goldSoft: "#e4c78a",
      goldDark: "#a8792b",
      ivory: "#fffaf4",
      onyx: "#1b1512",
      sidebar: "#f0e7dc",
      sidebarForeground: "#201915",
      sidebarPrimary: "#c89b4a",
      sidebarPrimaryForeground: "#fffaf4",
      sidebarAccent: "#e4d6c1",
      sidebarAccentForeground: "#201915",
      sidebarBorder: "#d7c1a7",
      sidebarRing: "#c89b4a",
      iconColor: "#6f5f54",
      displayFont: '"Playfair Display", "Cormorant Garamond", ui-serif, Georgia, serif',
      bodyFont: '"DM Sans", "Inter", ui-sans-serif, system-ui, sans-serif',
      buttonGradientStart: "#e4c78a",
      buttonGradientEnd: "#a8792b",
      buttonForeground: "#201915",
    },
  },
  {
    id: "champagne-rose",
    name: "Champagne Rose",
    description: "Creamy ivory with blush taupe and warm jewelry gold.",
    category: "Soft Elegant",
    colors: {
      background: "#f8f1e7",
      foreground: "#3d312b",
      card: "#fffaf3",
      cardForeground: "#3d312b",
      popover: "#fffaf3",
      popoverForeground: "#3d312b",
      primary: "#9f6350",
      primaryForeground: "#fffaf3",
      secondary: "#e8dccf",
      secondaryForeground: "#3d312b",
      muted: "#f0e7db",
      mutedForeground: "#8f8379",
      accent: "#ead8c8",
      accentForeground: "#3d312b",
      destructive: "#c46a5c",
      destructiveForeground: "#fffaf3",
      border: "#e1d3c4",
      input: "#eee3d6",
      ring: "#9f6350",
      gold: "#b99157",
      goldSoft: "#ead7a6",
      goldDark: "#8d6534",
      ivory: "#fffaf3",
      onyx: "#1f1916",
      sidebar: "#f5ede4",
      sidebarForeground: "#3d312b",
      sidebarPrimary: "#9f6350",
      sidebarPrimaryForeground: "#fffaf3",
      sidebarAccent: "#e9ddcf",
      sidebarAccentForeground: "#3d312b",
      sidebarBorder: "#dccdbd",
      sidebarRing: "#9f6350",
      iconColor: "#a18f82",
      displayFont: '"Cormorant Garamond", "Playfair Display", ui-serif, Georgia, serif',
      bodyFont: '"DM Sans", "Inter", ui-sans-serif, system-ui, sans-serif',
      buttonGradientStart: "#cfad73",
      buttonGradientEnd: "#9f6350",
      buttonForeground: "#fffaf3",
    },
  },
  {
    id: "pearl-sand",
    name: "Pearl Sand",
    description: "Airy pearl whites with soft sand and champagne accents.",
    category: "Soft Elegant",
    colors: {
      background: "#fcf7ef",
      foreground: "#3f352f",
      card: "#fffdf8",
      cardForeground: "#3f352f",
      popover: "#fffdf8",
      popoverForeground: "#3f352f",
      primary: "#b58c62",
      primaryForeground: "#fffdf8",
      secondary: "#efe6d9",
      secondaryForeground: "#3f352f",
      muted: "#f4ece2",
      mutedForeground: "#8f8478",
      accent: "#eadfce",
      accentForeground: "#3f352f",
      destructive: "#c46a5c",
      destructiveForeground: "#fffdf8",
      border: "#e5d9c9",
      input: "#efe4d6",
      ring: "#b58c62",
      gold: "#c8a46d",
      goldSoft: "#ecd9b1",
      goldDark: "#936d3f",
      ivory: "#fffdf8",
      onyx: "#1d1714",
      sidebar: "#f7efe5",
      sidebarForeground: "#3f352f",
      sidebarPrimary: "#b58c62",
      sidebarPrimaryForeground: "#fffdf8",
      sidebarAccent: "#eadfce",
      sidebarAccentForeground: "#3f352f",
      sidebarBorder: "#dccfbe",
      sidebarRing: "#b58c62",
      iconColor: "#8f8478",
      displayFont: '"Cormorant Garamond", "Playfair Display", ui-serif, Georgia, serif',
      bodyFont: '"Inter", ui-sans-serif, system-ui, sans-serif',
      buttonGradientStart: "#e2c89d",
      buttonGradientEnd: "#b58c62",
      buttonForeground: "#3f352f",
    },
  },
  {
    id: "cream-olive-sand",
    name: "Cream Olive Sand",
    description: "Soft cream with grounded olive and warm sand accents.",
    category: "Soft Elegant",
    colors: {
      background: "#fff6e6",
      foreground: "#2D3621",
      card: "#fffdf8",
      cardForeground: "#2D3621",
      popover: "#fffdf8",
      popoverForeground: "#2D3621",
      primary: "#D3BF88",
      primaryForeground: "#2D3621",
      secondary: "#f1e5cf",
      secondaryForeground: "#2D3621",
      muted: "#f6eddc",
      mutedForeground: "#6b715d",
      accent: "#e2d2af",
      accentForeground: "#2D3621",
      destructive: "#c46a5c",
      destructiveForeground: "#fffdf8",
      border: "#d8cab0",
      input: "#eadfca",
      ring: "#D3BF88",
      gold: "#D3BF88",
      goldSoft: "#eadbb7",
      goldDark: "#a78f55",
      ivory: "#fffdf8",
      onyx: "#1b1f16",
      sidebar: "#f5ebd8",
      sidebarForeground: "#2D3621",
      sidebarPrimary: "#D3BF88",
      sidebarPrimaryForeground: "#2D3621",
      sidebarAccent: "#e7d9bc",
      sidebarAccentForeground: "#2D3621",
      sidebarBorder: "#d5c6a6",
      sidebarRing: "#D3BF88",
      iconColor: "#6b715d",
      displayFont: '"Cormorant Garamond", "Playfair Display", ui-serif, Georgia, serif',
      bodyFont: '"Inter", ui-sans-serif, system-ui, sans-serif',
      buttonGradientStart: "#eadbb7",
      buttonGradientEnd: "#D3BF88",
      buttonForeground: "#2D3621",
    },
  },
  {
    id: "ivory-champagne",
    name: "Ivory Champagne",
    description: "Warm ivory and champagne with a refined editorial feel.",
    category: "Soft Elegant",
    colors: {
      background: "#f9f4ea",
      foreground: "#322922",
      card: "#fffdf8",
      cardForeground: "#322922",
      popover: "#fffdf8",
      popoverForeground: "#322922",
      primary: "#a56f59",
      primaryForeground: "#fffdf8",
      secondary: "#ede1d2",
      secondaryForeground: "#322922",
      muted: "#f2e8dc",
      mutedForeground: "#87796f",
      accent: "#e8dac7",
      accentForeground: "#322922",
      destructive: "#bf665b",
      destructiveForeground: "#fffdf8",
      border: "#e1d3c2",
      input: "#eee1d2",
      ring: "#a56f59",
      gold: "#bf985d",
      goldSoft: "#ead8aa",
      goldDark: "#8a6537",
      ivory: "#fffdf8",
      onyx: "#1c1613",
      sidebar: "#f4ecdf",
      sidebarForeground: "#322922",
      sidebarPrimary: "#a56f59",
      sidebarPrimaryForeground: "#fffdf8",
      sidebarAccent: "#e8dac7",
      sidebarAccentForeground: "#322922",
      sidebarBorder: "#d9caba",
      sidebarRing: "#a56f59",
      iconColor: "#87796f",
      displayFont: '"Playfair Display", "Cormorant Garamond", ui-serif, Georgia, serif',
      bodyFont: '"DM Sans", "Inter", ui-sans-serif, system-ui, sans-serif',
      buttonGradientStart: "#e0c78f",
      buttonGradientEnd: "#a56f59",
      buttonForeground: "#fffdf8",
    },
  },
  {
    id: "emerald-luxe",
    name: "Emerald Luxe",
    description: "Elegant emerald tones with gold highlights.",
    category: "Bold Jewel",
    colors: {
      background: "#101815",
      foreground: "#f2efe8",
      card: "#17221d",
      cardForeground: "#f2efe8",
      popover: "#17221d",
      popoverForeground: "#f2efe8",
      primary: "#c9a24d",
      primaryForeground: "#101815",
      secondary: "#203029",
      secondaryForeground: "#f2efe8",
      muted: "#1a261f",
      mutedForeground: "#b7c0b8",
      accent: "#274136",
      accentForeground: "#f2efe8",
      border: "#4a6356",
      input: "#223229",
      ring: "#c9a24d",
      gold: "#c9a24d",
      goldSoft: "#e8cf8e",
      goldDark: "#9d7b35",
      ivory: "#f2efe8",
      onyx: "#0b120f",
      sidebar: "#0d1311",
      sidebarForeground: "#e8efe8",
      sidebarPrimary: "#c9a24d",
      sidebarPrimaryForeground: "#101815",
      sidebarAccent: "#1d2a24",
      sidebarAccentForeground: "#f2efe8",
      sidebarBorder: "#395043",
      sidebarRing: "#c9a24d",
      iconColor: "#b7c0b8",
      displayFont: '"Cinzel", "Cormorant Garamond", ui-serif, Georgia, serif',
      bodyFont: '"Manrope", "Inter", ui-sans-serif, system-ui, sans-serif',
      buttonGradientStart: "#e8cf8e",
      buttonGradientEnd: "#9d7b35",
      buttonForeground: "#101815",
    },
  },
  {
    id: "burgundy-royal",
    name: "Burgundy Royal",
    description: "Rich burgundy with regal gold contrast.",
    category: "Bold Jewel",
    colors: {
      background: "#1b1216",
      foreground: "#f7efe9",
      card: "#28181f",
      cardForeground: "#f7efe9",
      popover: "#28181f",
      popoverForeground: "#f7efe9",
      primary: "#d1a15d",
      primaryForeground: "#1b1216",
      secondary: "#3a2028",
      secondaryForeground: "#f7efe9",
      muted: "#2d1b22",
      mutedForeground: "#ceb8bc",
      accent: "#472632",
      accentForeground: "#f7efe9",
      border: "#6a4954",
      input: "#372129",
      ring: "#d1a15d",
      gold: "#d1a15d",
      goldSoft: "#ebd19f",
      goldDark: "#9e7434",
      ivory: "#f7efe9",
      onyx: "#120c0e",
      sidebar: "#140d11",
      sidebarForeground: "#f2e6e8",
      sidebarPrimary: "#d1a15d",
      sidebarPrimaryForeground: "#1b1216",
      sidebarAccent: "#2c1c22",
      sidebarAccentForeground: "#f7efe9",
      sidebarBorder: "#553844",
      sidebarRing: "#d1a15d",
      iconColor: "#ceb8bc",
      displayFont: '"Cormorant Garamond", "Playfair Display", ui-serif, Georgia, serif',
      bodyFont: '"Inter", ui-sans-serif, system-ui, sans-serif',
      buttonGradientStart: "#ebd19f",
      buttonGradientEnd: "#9e7434",
      buttonForeground: "#1b1216",
    },
  },
  {
    id: "slate-champagne",
    name: "Slate Champagne",
    description: "Cool slate balanced with soft champagne gold.",
    category: "Cool Modern",
    colors: {
      background: "#11161d",
      foreground: "#f3f4f6",
      card: "#18212b",
      cardForeground: "#f3f4f6",
      popover: "#18212b",
      popoverForeground: "#f3f4f6",
      primary: "#d6b06a",
      primaryForeground: "#11161d",
      secondary: "#243140",
      secondaryForeground: "#f3f4f6",
      muted: "#1b2430",
      mutedForeground: "#b5bfcb",
      accent: "#2d3b4d",
      accentForeground: "#f3f4f6",
      border: "#506174",
      input: "#203040",
      ring: "#d6b06a",
      gold: "#d6b06a",
      goldSoft: "#ecd7a6",
      goldDark: "#a88439",
      ivory: "#f3f4f6",
      onyx: "#0b0f14",
      sidebar: "#0d1117",
      sidebarForeground: "#eef2f7",
      sidebarPrimary: "#d6b06a",
      sidebarPrimaryForeground: "#11161d",
      sidebarAccent: "#1d2735",
      sidebarAccentForeground: "#f3f4f6",
      sidebarBorder: "#3b4a5a",
      sidebarRing: "#d6b06a",
      iconColor: "#b5bfcb",
      displayFont: '"Merriweather", "Cormorant Garamond", ui-serif, Georgia, serif',
      bodyFont: '"Source Sans 3", "Inter", ui-sans-serif, system-ui, sans-serif',
      buttonGradientStart: "#ecd7a6",
      buttonGradientEnd: "#a88439",
      buttonForeground: "#11161d",
    },
  },
  {
    id: "rose-quartz",
    name: "Rose Quartz",
    description: "Soft romantic pinks with warm gold detail.",
    category: "Soft Elegant",
    colors: {
      background: "#f7eef1",
      foreground: "#24191d",
      card: "#fff8fa",
      cardForeground: "#24191d",
      popover: "#fff8fa",
      popoverForeground: "#24191d",
      primary: "#c99679",
      primaryForeground: "#fff8fa",
      secondary: "#ead8dd",
      secondaryForeground: "#24191d",
      muted: "#f1e3e7",
      mutedForeground: "#7b5e66",
      accent: "#e7cdd4",
      accentForeground: "#24191d",
      border: "#d8b9c2",
      input: "#e7d1d8",
      ring: "#c99679",
      gold: "#c99679",
      goldSoft: "#ead0be",
      goldDark: "#9d6f56",
      ivory: "#fff8fa",
      onyx: "#170f11",
      sidebar: "#f0e3e7",
      sidebarForeground: "#24191d",
      sidebarPrimary: "#c99679",
      sidebarPrimaryForeground: "#fff8fa",
      sidebarAccent: "#e3ccd2",
      sidebarAccentForeground: "#24191d",
      sidebarBorder: "#cfb2bb",
      sidebarRing: "#c99679",
      iconColor: "#7b5e66",
      displayFont: '"Playfair Display", "Cormorant Garamond", ui-serif, Georgia, serif',
      bodyFont: '"DM Sans", "Inter", ui-sans-serif, system-ui, sans-serif',
      buttonGradientStart: "#ead0be",
      buttonGradientEnd: "#9d6f56",
      buttonForeground: "#24191d",
    },
  },
  {
    id: "midnight-sapphire",
    name: "Midnight Sapphire",
    description: "Moody navy tones with luminous gold.",
    category: "Dark Luxury",
    colors: {
      background: "#0e1420",
      foreground: "#f4f6fb",
      card: "#151d2b",
      cardForeground: "#f4f6fb",
      popover: "#151d2b",
      popoverForeground: "#f4f6fb",
      primary: "#d8b15d",
      primaryForeground: "#0e1420",
      secondary: "#1d2a3d",
      secondaryForeground: "#f4f6fb",
      muted: "#182235",
      mutedForeground: "#b8c1d4",
      accent: "#22324a",
      accentForeground: "#f4f6fb",
      border: "#40526f",
      input: "#1c2940",
      ring: "#d8b15d",
      gold: "#d8b15d",
      goldSoft: "#ecd6a0",
      goldDark: "#a27d34",
      ivory: "#f4f6fb",
      onyx: "#090d14",
      sidebar: "#0b101a",
      sidebarForeground: "#eef2fb",
      sidebarPrimary: "#d8b15d",
      sidebarPrimaryForeground: "#0e1420",
      sidebarAccent: "#182235",
      sidebarAccentForeground: "#f4f6fb",
      sidebarBorder: "#32415a",
      sidebarRing: "#d8b15d",
      iconColor: "#b8c1d4",
      displayFont: '"Cormorant Garamond", "Playfair Display", ui-serif, Georgia, serif',
      bodyFont: '"Inter", ui-sans-serif, system-ui, sans-serif',
      buttonGradientStart: "#ecd6a0",
      buttonGradientEnd: "#a27d34",
      buttonForeground: "#0e1420",
    },
  },
  {
    id: "desert-pearl",
    name: "Desert Pearl",
    description: "Neutral sand with pearl-like softness.",
    category: "Soft Elegant",
    colors: {
      background: "#f6f0e6",
      foreground: "#2b231c",
      card: "#fffaf2",
      cardForeground: "#2b231c",
      popover: "#fffaf2",
      popoverForeground: "#2b231c",
      primary: "#b98f53",
      primaryForeground: "#fffaf2",
      secondary: "#ebe0d1",
      secondaryForeground: "#2b231c",
      muted: "#efe6da",
      mutedForeground: "#857468",
      accent: "#e4d6c4",
      accentForeground: "#2b231c",
      border: "#d7c6b2",
      input: "#e6d8c7",
      ring: "#b98f53",
      gold: "#b98f53",
      goldSoft: "#e2c894",
      goldDark: "#8f6831",
      ivory: "#fffaf2",
      onyx: "#1d1712",
      sidebar: "#eee4d7",
      sidebarForeground: "#2b231c",
      sidebarPrimary: "#b98f53",
      sidebarPrimaryForeground: "#fffaf2",
      sidebarAccent: "#e2d5c6",
      sidebarAccentForeground: "#2b231c",
      sidebarBorder: "#d4c1ac",
      sidebarRing: "#b98f53",
      iconColor: "#857468",
      displayFont: '"Cormorant Garamond", "Playfair Display", ui-serif, Georgia, serif',
      bodyFont: '"Source Sans 3", "Inter", ui-sans-serif, system-ui, sans-serif',
      buttonGradientStart: "#e2c894",
      buttonGradientEnd: "#8f6831",
      buttonForeground: "#2b231c",
    },
  },
  {
    id: "charcoal-amber",
    name: "Charcoal Amber",
    description: "Dark charcoal with amber warmth.",
    category: "Dark Luxury",
    colors: {
      background: "#151515",
      foreground: "#f5efe6",
      card: "#202020",
      cardForeground: "#f5efe6",
      popover: "#202020",
      popoverForeground: "#f5efe6",
      primary: "#d39a4b",
      primaryForeground: "#151515",
      secondary: "#292524",
      secondaryForeground: "#f5efe6",
      muted: "#23201f",
      mutedForeground: "#c9b9a2",
      accent: "#312d2a",
      accentForeground: "#f5efe6",
      border: "#4a4440",
      input: "#2b2724",
      ring: "#d39a4b",
      gold: "#d39a4b",
      goldSoft: "#e8c98f",
      goldDark: "#a06f2e",
      ivory: "#f5efe6",
      onyx: "#0d0d0d",
      sidebar: "#101010",
      sidebarForeground: "#f0e7da",
      sidebarPrimary: "#d39a4b",
      sidebarPrimaryForeground: "#151515",
      sidebarAccent: "#25201d",
      sidebarAccentForeground: "#f5efe6",
      sidebarBorder: "#3c3732",
      sidebarRing: "#d39a4b",
      iconColor: "#c9b9a2",
      displayFont: '"Merriweather", "Cormorant Garamond", ui-serif, Georgia, serif',
      bodyFont: '"Inter", ui-sans-serif, system-ui, sans-serif',
      buttonGradientStart: "#e8c98f",
      buttonGradientEnd: "#a06f2e",
      buttonForeground: "#151515",
    },
  },
  {
    id: "ocean-mist",
    name: "Ocean Mist",
    description: "Cool coastal neutrals with soft gold.",
    category: "Cool Modern",
    colors: {
      background: "#eef4f7",
      foreground: "#1d2730",
      card: "#f8fbfd",
      cardForeground: "#1d2730",
      popover: "#f8fbfd",
      popoverForeground: "#1d2730",
      primary: "#c3a15b",
      primaryForeground: "#f8fbfd",
      secondary: "#dce7ee",
      secondaryForeground: "#1d2730",
      muted: "#e5edf2",
      mutedForeground: "#667785",
      accent: "#d0dde6",
      accentForeground: "#1d2730",
      border: "#c0cfda",
      input: "#d7e1e8",
      ring: "#c3a15b",
      gold: "#c3a15b",
      goldSoft: "#e3cf9b",
      goldDark: "#9a7732",
      ivory: "#f8fbfd",
      onyx: "#11181f",
      sidebar: "#e8f0f4",
      sidebarForeground: "#1d2730",
      sidebarPrimary: "#c3a15b",
      sidebarPrimaryForeground: "#f8fbfd",
      sidebarAccent: "#d9e4ea",
      sidebarAccentForeground: "#1d2730",
      sidebarBorder: "#c7d3dc",
      sidebarRing: "#c3a15b",
      iconColor: "#667785",
      displayFont: '"Playfair Display", "Cormorant Garamond", ui-serif, Georgia, serif',
      bodyFont: '"Manrope", "Inter", ui-sans-serif, system-ui, sans-serif',
      buttonGradientStart: "#e3cf9b",
      buttonGradientEnd: "#9a7732",
      buttonForeground: "#11181f",
    },
  },
];

export const THEME_PRESET_CATEGORIES: Array<ThemePreset["category"]> = [
  "Dark Luxury",
  "Soft Elegant",
  "Bold Jewel",
  "Cool Modern",
];

export function createThemeForm(overrides?: ThemeColors | null): Record<ThemeColorKey, string> {
  return {
    ...DEFAULT_THEME_FORM,
    ...(overrides ?? {}),
  };
}

const CSS_VAR_MAP: Record<ThemeColorKey, string> = {
  background: "--background",
  foreground: "--foreground",
  card: "--card",
  cardForeground: "--card-foreground",
  popover: "--popover",
  popoverForeground: "--popover-foreground",
  primary: "--primary",
  primaryForeground: "--primary-foreground",
  secondary: "--secondary",
  secondaryForeground: "--secondary-foreground",
  muted: "--muted",
  mutedForeground: "--muted-foreground",
  accent: "--accent",
  accentForeground: "--accent-foreground",
  destructive: "--destructive",
  destructiveForeground: "--destructive-foreground",
  border: "--border",
  input: "--input",
  ring: "--ring",
  gold: "--gold",
  goldSoft: "--gold-soft",
  goldDark: "--gold-dark",
  ivory: "--ivory",
  onyx: "--onyx",
  sidebar: "--sidebar",
  sidebarForeground: "--sidebar-foreground",
  sidebarPrimary: "--sidebar-primary",
  sidebarPrimaryForeground: "--sidebar-primary-foreground",
  sidebarAccent: "--sidebar-accent",
  sidebarAccentForeground: "--sidebar-accent-foreground",
  sidebarBorder: "--sidebar-border",
  sidebarRing: "--sidebar-ring",
  iconColor: "--icon-color",
  displayFont: "--font-display",
  bodyFont: "--font-sans",
  buttonGradientStart: "--button-gradient-start",
  buttonGradientEnd: "--button-gradient-end",
  buttonForeground: "--button-foreground",
};

export function applyThemeColors(theme?: ThemeColors | null) {
  if (typeof document === "undefined") return;

  const root = document.documentElement;
  for (const [key, cssVar] of Object.entries(CSS_VAR_MAP) as Array<[ThemeColorKey, string]>) {
    const value = theme?.[key];
    if (value) root.style.setProperty(cssVar, value);
    else root.style.removeProperty(cssVar);
  }
}
